name: styles
description: A new Flutter project.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  email_validator: ^2.1.17
  intl_phone_field: ^3.2.0
  pinput: ^2.2.16
  firebase_auth: ^5.3.1
  provider: ^6.0.5
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4
  smooth_page_indicator: ^1.2.0+3
  snapkit_flutter: ^0.0.1
  country_code_picker: ^2.0.1
  intl_phone_number_input: ^0.7.0+2
  deepar_flutter: ^0.0.5
  image_picker: ^1.1.2
  firebase_storage: ^12.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1 # Use the latest version
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/logo/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "lib/assets/logo/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "lib/assets/logo/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "lib/assets/logo/logo.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/google.png
    - lib/assets/logo/logo.png
    - lib/assets/
    - lib/assets/images/hero_banner.png
    - assets/filters/
    - assets/previews/
    - lib/assets/images/oval_men.png
    - lib/assets/images/round_men.png
    - lib/assets/images/square_men.png
    - lib/assets/images/heart_men.png
    - lib/assets/images/wavy_men.png
    - lib/assets/images/straight_men.png
    - lib/assets/images/curly_men.png
    - lib/assets/images/coily_men.png
